# Generated by Django 4.0.6 on 2022-08-05 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.IntegerField(default=5)),
                ('weights', models.CharField(default='1,1,1,1,1', max_length=100)),
                ('impacts', models.CharField(default='+,+,+,+,+', max_length=100)),
                ('file', models.TextField(default=None, null=True)),
                ('add', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
